# Generated by Django 5.0 on 2023-12-22 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_category_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), default=list, size=5),
        ),
    ]
