# Generated by Django 5.0 on 2023-12-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_alter_items_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
